druid:
  type: com.alibaba.druid.pool.DruidDataSource
  smaug:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 10
    min-idle: 1
    max-active: 10
    test-on-borrow: true
    demo:
      url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
    article:
      url: jdbc:mysql://localhost:3306/xiaoyun?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456
    queue:
          url: jdbc:mysql://10.0.21.66:3306/queues?useUnicode=true&characterEncoding=utf8&useSSL=true
          username: 9now_dev
          password: 9now.321
    shop:
          url: jdbc:mysql://10.0.21.66:3306/restaurant?useUnicode=true&characterEncoding=utf8&useSSL=true
          username: 9now_dev
          password: 9now.321
